### ISSUE TITLE
No redtext

### ISSUE THREAD

**Issue by installgen2** [tux3/qTox#2218]
Any good messaging client needs to give user the ability to redtext.
Redtext is accomplished by using a reverse/backwards meme arrow at the end of your text, and colours the text red, much like how greentext works, but better.

**Comment by wiiam** [comment]
I also give this my upboat. Effective memeing does not come without redtexting

**Comment by agilob** [comment]
This feature must be implemented on all clients. I can't be qtox-only feature.

**Comment by installgen2** [comment]
uTox has it: https://github.com/GrayHatter/utox/commit/d79822af20e7d69679b3e45013ca687ab2ecff03

**Comment by suhr** [comment]
Your feature will break abstract algebra text. For example, `< x | x^n = e>`.

**Comment by agilob** [comment]
And there will be conflict with `>.<`

**Comment by 5JW** [comment]
Just like greentext, redtext is used by many people to express specific emotions and certain tones of voice. In order for this to be a proper fully complete communication platform redtext is an absolute necessity.

**Comment by ProMcTagonist** [comment]
@suhr 
>break

No. The text changing color does not break anything. I can't wait to go through this again with a new color.

**Comment by installgen2** [comment]
Also, if you really want, you can stop it from matching unintended things

**Comment by zetok** [comment]
>No redtext

Yes.

**Comment by installgen2** [comment]
I think I'm being oppressed

**Comment by zetok** [comment]
What would make you think so?

**Comment by installgen2** [comment]
YOU'RE A FUCKING WHITE MALE

**Comment by zetok** [comment]
I see. Here have a cat pic :3
![cat-jump-fail](https://cloud.githubusercontent.com/assets/3148759/15258903/fa3a60f6-1945-11e6-9828-761aec4d8e45.gif)

I hope that this metaphor will help you see what is wrong with what you've written.

**Comment by installgen2** [comment]
racism = prejudice + power

you're a white male so you have power
and you have prejudice against funposters

you are a racist
that means you are oppressing me

I hope that cat is ok

**Comment by zetok** [comment]
Locking, since there's little to no constructive discussion.

@installgen2 
Now, qTox repo is not the place for insults. Take it somewhere else.
